name: jaguar_jwt
description: Provides JWT utilities for Dart including issuing a token, verifing a token and parsing a token.
version: 3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auth_header: ^3.0.1
  crypto: ^3.0.0

dev_dependencies:
  test: ^1.16.8
